### ISSUE TITLE
Design Thinking - Parte 1

### ISSUE THREAD

**Issue by rodrigoqfcosta** [rodrigoqfcosta/API-SPC#10]
Elaborar documentação com os seguintes requisitos

1. Criar empatia ou compreender:
- Consegue compartilhar a dor de nosso cliente;
- Consegue compartilhar das necessidades do cliente;
- Colocar-se no lugar de nosso cliente (SPC) e ver o mundo pela sua perpectiva.

2. Definir
- Identificar onde encontrar oportunidade de inovação;
- O que nos sabemos do problema?
- Como desejamos fazer a diferença na vida das pessoas?
- Qual o valor da solução? agregar valor.
Ferramentas: PM Canvas Visual

3.   Ideia
- Visualização das Ideias;
- Seleção de ideias;
- Não julgar a ideia do outro;
- Ideias inovadoras.
Ferramantas: Brainstorming e votação em post-it

4. Protótipo
- Tirar a ideia da mente e colocar no mundo físico;
- Simples e rápido de aplicar;
- Intearação com pessoas, maior chance de sucesso;
- Idealizações inovadoras.
Ferramentas: Desenvolver o protótipo (Desenhos ou maquetes)

5. Testes
- Feedback precisos;
- Melhorias.
Ferramentas: Testes com dados dos usuários

**Comment by gusrobert** [comment]
Documentação sobre design thinking:
https://drive.google.com/file/d/1PAzx8LY2OvzbfOVOo1UHiFjBMB85Ean2/view?usp=sharing

**Comment by Stephanie345** [comment]
Exemplo de design thinking realizado na aula de gestão e governança de TI
https://drive.google.com/drive/folders/1icZSgcLx7JYnGAXbsbAZUoSS3kxJx2li

**Comment by Stephanie345** [comment]
Link da apresentação CANVAS em pptx
https://drive.google.com/file/d/10VLu_YugQTLo4jgyKGsde4wx1FEL40Ha/view?usp=sharing

**Comment by Stephanie345** [comment]
Protótipo das telas do dashboard realizado no FIGMA
https://www.figma.com/file/IG2nL9C1MjWlJsDXPkW92r/Figma-Admin-Dashboard-UI-Kit-Community?node-id=0%3A1

**Comment by Stephanie345** [comment]
Arquivo doc do Desing Thinking
https://drive.google.com/file/d/1ojrjRXKyoY9e-EaUigtTEvjsB-v3ktJH/view?usp=sharing
